### ISSUE TITLE
Internal stream write error

### ISSUE THREAD

**Issue by JanStreffing** [UNICORE-EU/uftp#19]
While transfering data between Korea and Germany I now frequently get the following error, which follows a long period of inactivity close to the end of the data transfer. Are there any options that I can set, to make the transfer more stable? 
I tried reducing streams to 1 and threads to 1, while this cost a lot of tranfer speed, it did not make the error go away.

Command:
`    uftp cp --identity $UFTP_KEY --streams 20 -t20 -T 1G -v $temp_dir/* $UFTP_AUTH_URL/$targetpath/$experiment/outdata/$model/`

Error:
```
oifs_skt_1m_TCo1279-DART-1950.part00  89%  8.5G [ 2.1MB/s | 2.1MB/s | 1.4MB/s | 1.8MB/s | 1.8MB/s | 1.7MB/s | 1.6MB/s | 915.5KB/s | 1.6MB/soifs_skt_1m_TCo1279-DART-1950.part00  89%  8.5G [ 2.1MB/s | 2.1MB/s | 1.4MB/s | 1.8MB/s | 1.8MB/s | 1.7MB/s | 1.6MB/s | 915.5KB/s | 1.6MB/s | 1.6MB/s | 1.5MB/s | 1.5MB/s | 1.4MB/s | 1.5MB/s | 1.3MB/s | 1.4MB/s ]  25.2MB/s                  2024-04-09 23:57:18,567 [UFTPClient-8] ERROR ClientPool - Error getting chunk [4547631067:5116084951] <//p/scratch/stresmodes/from_aleph//TCo1279-DART-1950/outdata/oifs/oifs_skt_1m_TCo1279-DART-1950.part00>
java.io.IOException: Internal stream write error
	at eu.unicore.uftp.jparss.POutputStream.writeParallel(POutputStream.java:259) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.jparss.POutputStream.write(POutputStream.java:229) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.client.UFTPSessionClient.moveData(UFTPSessionClient.java:521) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.client.UFTPSessionClient.moveData(UFTPSessionClient.java:500) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.client.UFTPSessionClient.put(UFTPSessionClient.java:183) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.standalone.ClientFacade.uploadFileChunk(ClientFacade.java:492) ~[uftp-client-1.5.0.jar:1.5.0]
	at eu.unicore.uftp.standalone.util.ClientPool$5.call(ClientPool.java:229) ~[uftp-client-1.5.0.jar:1.5.0]
	at eu.unicore.uftp.standalone.util.ClientPool$5.call(ClientPool.java:221) ~[uftp-client-1.5.0.jar:1.5.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-04-09 23:57:31,348 [UFTPClient-3] ERROR ClientPool - Error getting chunk [7389900492:7958354376] <//p/scratch/stresmodes/from_aleph//TCo1279-DART-1950/outdata/oifs/oifs_skt_1m_TCo1279-DART-1950.part00>
java.io.IOException: Internal stream write error
	at eu.unicore.uftp.jparss.POutputStream.writeParallel(POutputStream.java:259) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.jparss.POutputStream.write(POutputStream.java:229) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.client.UFTPSessionClient.moveData(UFTPSessionClient.java:521) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.client.UFTPSessionClient.moveData(UFTPSessionClient.java:500) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.client.UFTPSessionClient.put(UFTPSessionClient.java:183) ~[uftp-core-2.13.0.jar:2.13.0]
	at eu.unicore.uftp.standalone.ClientFacade.uploadFileChunk(ClientFacade.java:492) ~[uftp-client-1.5.0.jar:1.5.0]
	at eu.unicore.uftp.standalone.util.ClientPool$5.call(ClientPool.java:229) ~[uftp-client-1.5.0.jar:1.5.0]
	at eu.unicore.uftp.standalone.util.ClientPool$5.call(ClientPool.java:221) ~[uftp-client-1.5.0.jar:1.5.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-04-09 23:57:31,351 [main] ERROR ClientPool - java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Internal stream write error
2024-04-09 23:57:31,351 [main] ERROR ClientPool - java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Internal stream write error
^CuFTP operation failed.
```

**Comment by BerndSchuller** [comment]
hi,

threads and streams do different things... the error you see is related to streams > 1

Threads is the number of concurrent FTP sessions, while "streams" is the number of TCP connections per FTP session (i.e. per thread) (FYI, at Juelich, the max number of streams is "8", so any value larger than 8 will be limited to 8 anyway)

The "write error" indicates that one of the TCP connections was closed prematurely, probably by one of the (many) routers/switches/firewalls between the two endpoints...

As a client, there is not much you can do, I would however not use overly large numbers of threads, having 
20 threads and 8 streams means you have up to 160 TCP connections open.

the single thread data rates are really bad :-(  so I understand why you try with many sessions and streams.

In any case, I've slightly changed the configuration on the server at JSC, so TCP_KEEPALIVE is now enabled for data connections. That might(!) help with the prematurely closed connections.

If it still is unstable, I'm afraid you will need to write some additional reliability tooling on top of uftp.


hope this helps, and best regards,
Bernd
